### ISSUE TITLE
using `min_opt` in List0.max?

### ISSUE THREAD

**Issue by anz-ryu** [kxcinc/kxclib-ocaml#48]
ref: 
https://github.com/kxcinc/kxclib-ocaml/blob/f608f62d2303f43643ae9277759a67503ffa8bd3/kxclib.ml#L1006

**Comment by anz-ryu** [comment]
@haochenx(cc: @kxc-waddlaw ) さん
これは意図的でしょうか、ミスでしょうか、ミスであればPRを出します。

**Comment by haochenx** [comment]
fixed in https://github.com/kxcinc/kxclib-ocaml/commit/75e7d286b63e94b565858bf978904d6c541bbebe
